---
- name: Post a slack message with details of a vulnerable workload
  hosts: localhost
  become: no
  vars_files:
    - vault.yml

  tasks:
    - name: Get an access token from OpenShift
      kubernetes.core.k8s_auth:
        username: "{{ vault_openshift_user }}"
        password: "{{ vault_openshift_pass }}"
        host: "{{ vault_openshift_host }}"
        validate_certs: false
      register: k8s_auth_results

    - name: Fetch a specific deployment from OpenShift by name
      kubernetes.core.k8s_info:
        api_key: "{{ k8s_auth_results.openshift_auth.api_key }}"
        host: "{{ vault_openshift_host }}"
        validate_certs: false
        kind: Deployment
        name: "{{ deployment_name }}"
        namespace: "{{ deployment_namespace }}"
      register: deployment

    - name: Post a slack message
      community.general.slack:
        token: "{{ vault_slack_token }}"
        msg: |
            Dynatrace has detected Log4Shell exploitation attempts against the following workload: 
                        
            Cluster: OpenShift production
            Namespace: "{{ deployment_namespace }}"
            Deployment name: "{{ deployment_name }}"
            Image: "{{ deployment.resources[0].spec.template.spec.containers[0].image }}"

            Red Hat Advanced Cluster Security for Kubernetes policies have been updated:

            - Curl execution policy applied
            - Netcat execution policy applied
            - Kubernetes network policy locked down
            - Slack integration created with this channel

        channel: "#devops"
        color: good


